//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpikeContainer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MANUFACTURING;Initial Catalog=TestMesDb;Integrated Security=True")]
        public string TestMesDbConnectionString {
            get {
                return ((string)(this["TestMesDbConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ominvore")]
        public string MainPassword {
            get {
                return ((string)(this["MainPassword"]));
            }
            set {
                this["MainPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Marlin Perkins")]
        public string SpecialUser {
            get {
                return ((string)(this["SpecialUser"]));
            }
            set {
                this["SpecialUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WildKindom")]
        public string SpecialDomain {
            get {
                return ((string)(this["SpecialDomain"]));
            }
            set {
                this["SpecialDomain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2017-09-24")]
        public string LastPTMELogRunTime {
            get {
                return ((string)(this["LastPTMELogRunTime"]));
            }
            set {
                this["LastPTMELogRunTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A big boinking Monitor")]
        public string ScreenSize {
            get {
                return ((string)(this["ScreenSize"]));
            }
            set {
                this["ScreenSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fine fine detail")]
        public string ScreenResolution {
            get {
                return ((string)(this["ScreenResolution"]));
            }
            set {
                this["ScreenResolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>\\laqad.Malden.com\SigConnects\Arch_Old</string>
  <string>\\laqad.Malden.com\SigConnects\Arch_Old1</string>
  <string>\\laqad.Malden.com\SigConnects\Arch_Old2</string>
  <string>Arch_Old</string>
  <string>SigConnects\Arch_Old</string>
  <string>\Arch_Old</string>
  <string>\SigConnects\Arch_Old</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ExcludedDirectories {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ExcludedDirectories"]));
            }
            set {
                this["ExcludedDirectories"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2018-04-09")]
        public global::System.DateTime LastServiceRunTime {
            get {
                return ((global::System.DateTime)(this["LastServiceRunTime"]));
            }
            set {
                this["LastServiceRunTime"] = value;
            }
        }
    }
}
