//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpikeContainer.DataEntitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArelContainer
    {
        public int Arel_Key { get; set; }
        public short MachineNo { get; set; }
        public string LotNo { get; set; }
        public short DyeProgramNo { get; set; }
        public Nullable<short> NBofcontainers { get; set; }
        public string Batch__1 { get; set; }
        public string Batch__2 { get; set; }
        public string Batch__3 { get; set; }
        public string Batch__4 { get; set; }
        public string Batch__5 { get; set; }
        public string Batch__6 { get; set; }
        public string Batch__7 { get; set; }
        public string Batch__8 { get; set; }
        public string Batch__9 { get; set; }
        public string Batch__10 { get; set; }
        public string Batch__11 { get; set; }
        public string Batch__12 { get; set; }
        public string Batch__13 { get; set; }
        public string Batch__14 { get; set; }
        public string Batch__15 { get; set; }
        public string Batch__16 { get; set; }
        public string Batch__17 { get; set; }
        public string Batch__18 { get; set; }
        public string Batch__19 { get; set; }
        public string Batch__20 { get; set; }
        public string Container__1 { get; set; }
        public string Container__2 { get; set; }
        public string Container__3 { get; set; }
        public string Container__4 { get; set; }
        public string Container__5 { get; set; }
        public string Container__6 { get; set; }
        public string Container__7 { get; set; }
        public string Container__8 { get; set; }
        public string Container__9 { get; set; }
        public string Container__10 { get; set; }
        public string Container__11 { get; set; }
        public string Container__12 { get; set; }
        public string Container__13 { get; set; }
        public string Container__14 { get; set; }
        public string Container__15 { get; set; }
        public string Container__16 { get; set; }
        public string Container__17 { get; set; }
        public string Container__18 { get; set; }
        public string Container__19 { get; set; }
        public string Container__20 { get; set; }
        public string Warehouse__1 { get; set; }
        public string Warehouse__2 { get; set; }
        public string Warehouse__3 { get; set; }
        public string Warehouse__4 { get; set; }
        public string Warehouse__5 { get; set; }
        public string Warehouse__6 { get; set; }
        public string Warehouse__7 { get; set; }
        public string Warehouse__8 { get; set; }
        public string Warehouse__9 { get; set; }
        public string Warehouse__10 { get; set; }
        public string Warehouse__11 { get; set; }
        public string Warehouse__12 { get; set; }
        public string Warehouse__13 { get; set; }
        public string Warehouse__14 { get; set; }
        public string Warehouse__15 { get; set; }
        public string Warehouse__16 { get; set; }
        public string Warehouse__17 { get; set; }
        public string Warehouse__18 { get; set; }
        public string Warehouse__19 { get; set; }
        public string Warehouse__20 { get; set; }
        public Nullable<short> Number_of_pieces__1 { get; set; }
        public Nullable<short> Number_of_pieces__2 { get; set; }
        public Nullable<short> Number_of_pieces__3 { get; set; }
        public Nullable<short> Number_of_pieces__4 { get; set; }
        public Nullable<short> Number_of_pieces__5 { get; set; }
        public Nullable<short> Number_of_pieces__6 { get; set; }
        public Nullable<short> Number_of_pieces__7 { get; set; }
        public Nullable<short> Number_of_pieces__8 { get; set; }
        public Nullable<short> Number_of_pieces__9 { get; set; }
        public Nullable<short> Number_of_pieces__10 { get; set; }
        public Nullable<short> Number_of_pieces__11 { get; set; }
        public Nullable<short> Number_of_pieces__12 { get; set; }
        public Nullable<short> Number_of_pieces__13 { get; set; }
        public Nullable<short> Number_of_pieces__14 { get; set; }
        public Nullable<short> Number_of_pieces__15 { get; set; }
        public Nullable<short> Number_of_pieces__16 { get; set; }
        public Nullable<short> Number_of_pieces__17 { get; set; }
        public Nullable<short> Number_of_pieces__18 { get; set; }
        public Nullable<short> Number_of_pieces__19 { get; set; }
        public Nullable<short> Number_of_pieces__20 { get; set; }
        public string Sent_to_Munk { get; set; }
        public string Save_sent_to_munk { get; set; }
        public string Filler { get; set; }
    
        public virtual ArelLot ArelLot { get; set; }
    }
}
