//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpikeContainer.DataEntitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArelLot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArelLot()
        {
            this.ArelContainers = new HashSet<ArelContainer>();
            this.ArelLotsRecipes = new HashSet<ArelLotsRecipe>();
        }
    
        public string Lot_Number { get; set; }
        public Nullable<short> Weight { get; set; }
        public Nullable<short> Pump_Speed { get; set; }
        public Nullable<short> Roller_Speed { get; set; }
        public Nullable<short> Option1 { get; set; }
        public Nullable<short> Option2 { get; set; }
        public Nullable<short> Option3 { get; set; }
        public Nullable<short> Option4 { get; set; }
        public Nullable<short> Option5 { get; set; }
        public short Machine_nr { get; set; }
        public Nullable<short> Program_1 { get; set; }
        public string Status { get; set; }
        public string Lot_type { get; set; }
        public Nullable<short> Rolls { get; set; }
        public string Exported { get; set; }
        public string Filler { get; set; }
        public Nullable<int> Started_Date { get; set; }
        public Nullable<int> Started_Time { get; set; }
        public Nullable<int> End_____Date { get; set; }
        public Nullable<int> End_____Time { get; set; }
        public int Arel_Date { get; set; }
        public Nullable<short> Efc_Alarm_1 { get; set; }
        public Nullable<short> Efc_Alarm_2 { get; set; }
        public Nullable<short> Efc_Alarm_3 { get; set; }
        public Nullable<short> Efc_Alarm_4 { get; set; }
        public Nullable<short> Efc_Alarm_5 { get; set; }
        public Nullable<short> Efc_Alarm_6 { get; set; }
        public Nullable<short> Efc_Alarm_7 { get; set; }
        public Nullable<short> Efc_Alarm_8 { get; set; }
        public Nullable<short> Efc_Alarm_9 { get; set; }
        public Nullable<short> Efc_Alarm_10 { get; set; }
        public Nullable<short> Efc_Alarm_11 { get; set; }
        public Nullable<short> Efc_Alarm_12 { get; set; }
        public Nullable<short> Efc_Alarm_13 { get; set; }
        public Nullable<short> Efc_Alarm_14 { get; set; }
        public Nullable<short> Efc_Alarm_15 { get; set; }
        public Nullable<short> Efc_Alarm_16 { get; set; }
        public Nullable<int> Water_type_1 { get; set; }
        public Nullable<int> water_type_2 { get; set; }
        public Nullable<int> water_type_3 { get; set; }
        public Nullable<int> Water_Used_Blend { get; set; }
        public Nullable<int> Water_Used_For_Cool { get; set; }
        public Nullable<int> Main_Pump { get; set; }
        public Nullable<int> Roller_or_Auxilliary { get; set; }
        public Nullable<int> Chemicals_Pump { get; set; }
        public Nullable<int> Mixers { get; set; }
        public Nullable<int> Rinse_water_1 { get; set; }
        public Nullable<int> Rinse_water_2 { get; set; }
        public Nullable<int> Rinse_water_3 { get; set; }
        public Nullable<int> Rinse_blend { get; set; }
        public Nullable<int> Steam { get; set; }
        public string Customer { get; set; }
        public string Quality { get; set; }
        public string Shade { get; set; }
        public string Shade_Rating { get; set; }
        public Nullable<short> Width { get; set; }
        public Nullable<short> Length { get; set; }
        public string Batch_1 { get; set; }
        public string Batch_2 { get; set; }
        public string Batch_3 { get; set; }
        public string Batch_4 { get; set; }
        public string Batch_5 { get; set; }
        public string Batch_6 { get; set; }
        public string Batch_7 { get; set; }
        public string Batch_8 { get; set; }
        public string SpecialCode { get; set; }
        public string Spare { get; set; }
        public string Container__3 { get; set; }
        public string Container__4 { get; set; }
        public string Container__5 { get; set; }
        public string Container__6 { get; set; }
        public string Container__7 { get; set; }
        public string Container__8 { get; set; }
        public string Warehouse_1 { get; set; }
        public string Warehouse_2 { get; set; }
        public string Warehouse_3 { get; set; }
        public string Warehouse_4 { get; set; }
        public string Warehouse_5 { get; set; }
        public string Warehouse_6 { get; set; }
        public string Warehouse_7 { get; set; }
        public string Warehouse_8 { get; set; }
        public string Operator_ID { get; set; }
        public string Correction { get; set; }
        public Nullable<float> FloatWeight { get; set; }
        public Nullable<short> Rope_time { get; set; }
        public Nullable<short> OptimizedTime { get; set; }
        public Nullable<short> LotRedyeIndex { get; set; }
        public string SuperlotFlag { get; set; }
        public string SuperLotNo { get; set; }
        public Nullable<int> Length5 { get; set; }
        public string Filler1 { get; set; }
        public Nullable<System.DateTime> StartDT { get; set; }
        public Nullable<System.DateTime> EndDT { get; set; }
        public Nullable<short> ActTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArelContainer> ArelContainers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArelLotsRecipe> ArelLotsRecipes { get; set; }
    }
}
