//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpikeContainer.DataEntitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvailableGreige
    {
        public string SerialNo { get; set; }
        public Nullable<int> BinNo { get; set; }
        public string BinType { get; set; }
        public string Item { get; set; }
        public string KnitLot { get; set; }
        public Nullable<decimal> NetLbs { get; set; }
        public string Location { get; set; }
        public string PartialRoll { get; set; }
        public string PartialTub { get; set; }
        public Nullable<System.DateTime> RecDt { get; set; }
        public string StdMinRollWt { get; set; }
        public string StdRollsPerTub { get; set; }
        public string Status { get; set; }
        public Nullable<int> WorkOrder { get; set; }
    }
}
