//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpikeContainer.DataEntitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class DhPlanMstr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DhPlanMstr()
        {
            this.DhPlanDet = new HashSet<DhPlanDet>();
        }
    
        public string DyeLot { get; set; }
        public string Machine { get; set; }
        public int Seq { get; set; }
        public bool Scheduled { get; set; }
        public string Pool { get; set; }
        public string Rework { get; set; }
        public string ChangedBy { get; set; }
        public System.DateTime ChangedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DhPlanDet> DhPlanDet { get; set; }
    }
}
