//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpikeContainer.DataEntitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machines
    {
        public int MachId { get; set; }
        public string ShortName { get; set; }
        public string FullName { get; set; }
        public string MachType { get; set; }
        public string WorkCenter { get; set; }
        public string Dept { get; set; }
        public string QadMach { get; set; }
    }
}
