//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpikeContainer.DataEntitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Package()
        {
            this.PkgHists = new HashSet<PkgHist>();
        }
    
        public string SerialNo { get; set; }
        public int ShopOrderNo { get; set; }
        public string Item { get; set; }
        public string MasterItem { get; set; }
        public string Color { get; set; }
        public Nullable<int> LstOp { get; set; }
        public string LstMach { get; set; }
        public decimal AllowYds { get; set; }
        public decimal CutOffYds { get; set; }
        public string CutOffDefectCode { get; set; }
        public Nullable<float> FinWidth { get; set; }
        public string Grade { get; set; }
        public string QualCode { get; set; }
        public Nullable<decimal> GrossYds { get; set; }
        public Nullable<decimal> NetYds { get; set; }
        public Nullable<System.DateTime> InspBegTime { get; set; }
        public Nullable<System.DateTime> InspEndTime { get; set; }
        public decimal NetLbs { get; set; }
        public decimal TareLbs { get; set; }
        public string ReInspReqd { get; set; }
        public Nullable<System.DateTime> ReInspBegTime { get; set; }
        public Nullable<System.DateTime> ReInspEndTime { get; set; }
        public string HoldPiece { get; set; }
        public string HoldFor { get; set; }
        public string Reworked { get; set; }
        public string Rejected { get; set; }
        public string Warehouse { get; set; }
        public string Location { get; set; }
        public string Status { get; set; }
        public System.DateTime ChangedDate { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<int> BinNo { get; set; }
        public bool PackFlag { get; set; }
        public Nullable<int> LstShopOrder { get; set; }
        public bool FRFG { get; set; }
        public int DelschedID { get; set; }
        public string ShadeGroup { get; set; }
        public Nullable<bool> MilLotRep { get; set; }
    
        public virtual ShopOrder ShopOrder { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PkgHist> PkgHists { get; set; }
    }
}
