//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpikeContainer.DataEntitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShopOrder()
        {
            this.Packages = new HashSet<Package>();
        }
    
        public int ShopOrderNo { get; set; }
        public string Item { get; set; }
        public string MasterItem { get; set; }
        public string Color { get; set; }
        public int StdYds { get; set; }
        public int StdLbs { get; set; }
        public decimal ActStartLbs { get; set; }
        public Nullable<float> ActCurrLbs { get; set; }
        public Nullable<float> PkgCount { get; set; }
        public string DyeLot { get; set; }
        public string Status { get; set; }
        public string ChangedBy { get; set; }
        public System.DateTime ChangedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Package> Packages { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual User User { get; set; }
    }
}
