//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpikeContainer.DataEntitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemParams
    {
        public string Config { get; set; }
        public string Catalog { get; set; }
        public string AisCatalog { get; set; }
        public string company { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zipcode { get; set; }
        public string country { get; set; }
        public string phoneno { get; set; }
        public string plantno { get; set; }
        public string plantname { get; set; }
        public string updateDir { get; set; }
        public string smtpServer { get; set; }
        public string SSRSserverURI { get; set; }
        public string SSRSreportPath { get; set; }
        public string LabelsDir { get; set; }
        public string UpdateProgramSource { get; set; }
        public string SysUser { get; set; }
        public string SysHash { get; set; }
        public string AisUser { get; set; }
        public string AisHash { get; set; }
        public string SigConnFolder { get; set; }
    }
}
