//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpikeContainer.DataEntitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class WoConsuptionSteps
    {
        public int WorkOrder { get; set; }
        public int OpStepNo { get; set; }
        public string WorkCenter { get; set; }
        public string OpStep { get; set; }
        public bool Completed { get; set; }
    
        public virtual WorkOrders WorkOrders { get; set; }
    }
}
