//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpikeContainer.DataEntitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderTotals
    {
        public int WorkOrder { get; set; }
        public string Item { get; set; }
        public string MasterItem { get; set; }
        public string Color { get; set; }
        public string ComponentItem { get; set; }
        public string ItemDescr { get; set; }
        public string ColorDescr { get; set; }
        public string FormStyle { get; set; }
        public Nullable<int> WipPkgs { get; set; }
        public Nullable<int> LstOpStep { get; set; }
        public string LstOp { get; set; }
        public string LstMach { get; set; }
        public string NextOpStep { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> ReqYds { get; set; }
        public Nullable<decimal> ReqGrLbs { get; set; }
        public float ActStartLbs { get; set; }
        public float ActCheckLbs { get; set; }
        public Nullable<float> ProcYds { get; set; }
        public Nullable<decimal> OpenYds { get; set; }
        public Nullable<int> F_Rolls { get; set; }
        public Nullable<int> S_Rolls { get; set; }
        public Nullable<int> TotPackRolls { get; set; }
        public Nullable<decimal> F_Lbs { get; set; }
        public Nullable<decimal> S_Lbs { get; set; }
        public Nullable<decimal> TotPackLbs { get; set; }
        public Nullable<decimal> F_Yds { get; set; }
        public Nullable<decimal> S_Yds { get; set; }
        public Nullable<decimal> TotPackYds { get; set; }
        public Nullable<decimal> AllowYds { get; set; }
        public Nullable<decimal> CutOffYds { get; set; }
        public string DyeLot { get; set; }
        public Nullable<int> ParentWorkOrder { get; set; }
        public Nullable<System.DateTime> QcCheckInDt { get; set; }
        public string QcCheckInBy { get; set; }
        public Nullable<System.DateTime> QcReleasedDt { get; set; }
        public string QcReleasedBy { get; set; }
        public string ClosedBy { get; set; }
        public string MilLot { get; set; }
        public Nullable<System.DateTime> RelDate { get; set; }
        public Nullable<System.DateTime> Due { get; set; }
        public string SalesOrder { get; set; }
        public string SalesOrderLine { get; set; }
        public string OrdCust { get; set; }
        public string ArCust { get; set; }
        public string Brand { get; set; }
    }
}
