//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpikeContainer.DataEntitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderToRelease
    {
        public int WorkOrder { get; set; }
        public string Status { get; set; }
        public string Item { get; set; }
        public string ComponentItem { get; set; }
        public Nullable<decimal> ReqYds { get; set; }
        public Nullable<decimal> ReqGrLbs { get; set; }
        public Nullable<System.DateTime> Due { get; set; }
        public string Customer { get; set; }
        public Nullable<decimal> PickedLbs { get; set; }
        public Nullable<decimal> PickedYds { get; set; }
        public string DyeJet { get; set; }
        public string DyeSeq { get; set; }
    }
}
