//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpikeContainer.DataEntitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkOrders()
        {
            this.Packages = new HashSet<Packages>();
            this.WoConsuptionSteps = new HashSet<WoConsuptionSteps>();
        }
    
        public int WorkOrder { get; set; }
        public string Item { get; set; }
        public string MasterItem { get; set; }
        public string Color { get; set; }
        public float ActStartLbs { get; set; }
        public float ActCheckLbs { get; set; }
        public string Status { get; set; }
        public string DyeLot { get; set; }
        public Nullable<int> ParentWorkOrder { get; set; }
        public Nullable<System.DateTime> QcCheckInDt { get; set; }
        public string QcCheckInBy { get; set; }
        public Nullable<System.DateTime> QcReleasedDt { get; set; }
        public string QcReleasedBy { get; set; }
        public string MilLot { get; set; }
        public string ClosedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Packages> Packages { get; set; }
        public virtual Status Status1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WoConsuptionSteps> WoConsuptionSteps { get; set; }
    }
}
