//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpikeContainer.Spike_Dev_Express_Grid.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weights
    {
        public decimal GrossWeight { get; set; }
        public decimal TareWeight { get; set; }
        public decimal NetResultWeight { get; set; }
        public long Index { get; set; }
    }
}
