using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using EntityFramework.Extensions;
using System.Data.Entity;
using SpikeContainer.DataEntitiy;

namespace SpikeContainer.Spike_003
{
    public partial class Spike003Test001 : Form
    {

        private SpikeContainer.DataEntitiy.TestMesDbEntities _db;
        private string _user;

        public Spike003Test001()
        {
            InitializeComponent();

            ////////////// This line of code is generated by Data Source Configuration Wizard
            ////////////// Instantiate a new DBContext
            ////////////SpikeContainer.DataEntitiy.TestMesDbEntities dbContext = new SpikeContainer.DataEntitiy.TestMesDbEntities();
            ////////////// Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            ////////////dbContext.Users.LoadAsync().ContinueWith(loadTask =>
            ////////////{
            ////////////    // Bind data to control when loading complete
            ////////////    gridControl1.DataSource = dbContext.Users.Local.ToBindingList();
            ////////////}, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
            //// This line of code is generated by Data Source Configuration Wizard
            //// Instantiate a new DBContext
            //SpikeContainer.DataEntitiy.TestMesDbEntities dbContext = new SpikeContainer.DataEntitiy.TestMesDbEntities();
            //// Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            //dbContext.Users.Include("ShopOrders").Include("Permissions").LoadAsync().ContinueWith(loadTask =>
            //{
            //    // Bind data to control when loading complete
            //    usersBindingSource.DataSource = dbContext.Users.Local.ToBindingList();
            //    //usersBindingSource.DataSource = dbContext.ShopOrders.Local.ToBindingList();
            //}, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            SpikeContainer.DataEntitiy.TestMesDbEntities _db = new SpikeContainer.DataEntitiy.TestMesDbEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            _db.Users.Include("ShopOrders").Include("Permissions").LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                usersBindingSource.DataSource = _db.Users.Local.ToBindingList();
                //usersBindingSource.DataSource = dbContext.ShopOrders.Local.ToBindingList();
                //usersBindingSource.DataSource = dbContext.Permissions.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            InitializeAllData();
        }

        private void InitializeAllData()
        {
            _db?.Dispose();
            _db = new DataEntitiy.TestMesDbEntities();
            _db.Users.Include("ShopOrders").Include("Permissions").Load();
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            //gridControl1.DataSource = _db.Users.Local;
            //vGridControl1.DataSource = _db.Users.Local;
            //treeList1.DataSource = _db.Users.Local;
        }
    }
}
